version: '3.6'
services:
  redis:
    image: mararok/test-redis-cluster:${REDIS_IMAGE_VERSION}
    container_name: ${PROJECT}
    restart: always
    environment:
      - REDIS_CLUSTER_ANNOUNCE_PORT=${REDIS_HOST_PORT}
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ./tmp/redis:/bitnami/redis/data